detonastrike/urls.py
from django.contrib import admin
from django.urls import include, path # modificar esta linha

urlpatterns = [
    path('', include('staticpages.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path
from . import views

app_name = 'detonastrike'

urlpatterns = [
    path('', views.jogoListView.as_view(), name='index'),
    path('search/', views.search_movies, name='search'),
    path('<int:pk>/', views.jogoDetalheView.as_view(), name='detalhe'),
    path('create/', views.jogoCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.jogoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.jogoDeleteView.as_view(), name='delete'),
    path('review/<int:jogo_id>/', views.jogoReviewView, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create/', views.ListCreateView.as_view(), name='create_list'),
    path('detalist/<int:list_id>/', views.detal, name='detalist'),

    #path('<int:jg_id>/', views.detalhe, name='detalhe'),
    path('sobre', views.sobre, name='sobre'),
    #path('create', views.create_jogo, name='create'),
    #path('update/<int:jg_id>/', views.update_jogo, name='update'),
    #path('delete/<int:jg_id>/', views.delete_jogo, name='delete'),
    
]

staticpages/models.py
from django.db import models
from django.conf import settings


class jogo(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    poster_url = models.CharField(max_length=200, null=True)
    texto = models.CharField(max_length=1000, null=True)
    texto2 = models.CharField(max_length=1000, null=True)
    texto3 = models.CharField(max_length=1000, null=True)
    texto4 = models.CharField(max_length=1000, null=True)
    imagem1 = models.CharField(max_length=200, null=True)
    imagem2 = models.CharField(max_length=200, null=True)
    imagem3 = models.CharField(max_length=200, null=True)
    imagem4 = models.CharField(max_length=200, null=True)
    imagemdecapa = models.CharField(max_length=200, null=True)
    video1 = models.CharField(max_length=200, null=True)
    video2 = models.CharField(max_length=200, null=True)
    def __str__(self):
        return f'{self.name} ({self.release_year})'



class Review(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE, null=True)
    text = models.CharField(max_length=255, null=True)
    data = models.DateTimeField(null=True)
    jg = models.ForeignKey(jogo, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'"{self.text}""{self.data}"'



class List(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE,null=True)
    name = models.CharField(max_length=255, null=True)
    jg = models.ManyToManyField(jogo, null=True)

    def __str__(self):
        return f'{self.name} by {self.author}'

staticpages/views.py
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from .basededados import jg_data
from .models import jogo, Review, List
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, request
from django.urls import reverse, reverse_lazy
from django.views import generic
from datetime import date
from django.contrib.auth.decorators import login_required


def index(request):
    jogo_list = jogo.objects.all()
    context = {'jogo_list': jogo_list}
    return render(request, 'staticpages/index.html', context)

def sobre(request):
    context = {}
    return render(request, 'staticpages/sobre.html', context)


def detalhe(request, jg_id):
    jg = get_object_or_404(jogo, pk=jg_id)
    context = {'jg': jg}
    return render(request, 'staticpages/detalhe.html', context)


def search_jogo(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        jogo_list = jogo.objects.filter(name__icontains=search_term)
        context = {"jogo_list": jogo_list}
    return render(request, 'staticpages/search.html', context)

def create_jogo(request):
    if request.method == 'POST':
        name = request.POST['name']
        release_year = request.POST['release_year']
        poster_url = request.POST['poster_url']
        texto = request.POST['texto']
        texto2 = request.POST['texto2']
        texto3 = request.POST['texto3']
        texto4 = request.POST['texto4']
        imagem1 = request.POST['imagem1']
        imagem2 = request.POST['imagem2']
        imagem3 = request.POST['imagem3']
        imagem4 = request.POST['imagem4']
        imagemdecapa = request.POST['imagemdecapa']
        video1 = request.POST['video1']
        video2 = request.POST['video2']

        jg = jogo(name=name,
                      release_year=release_year,
                      poster_url=poster_url,
                      texto=texto,
                      texto2=texto2,
                      texto3=texto3,
                      texto4=texto4,
                      imagem1=imagem1,
                      imagem2=imagem2,
                      imagem3=imagem3,
                      imagem4=imagem4,
                      imagemdecapa=imagemdecapa,
                      video1=video1,
                      video2=video2)
        jg.save()
        return HttpResponseRedirect(
            reverse('detonastrike:detalhe', args=(jg.id,)))
    else:
        return render(request, 'staticpages/create.html', {})    



def update_jogo(request, jg_id):
    jg = get_object_or_404(jogo, pk=jg_id)

    if request.method == "POST":
        jg.name = request.POST['name']
        jg.release_year = request.POST['release_year']
        jg.poster_url = request.POST['poster_url']
        jg.texto = request.POST['texto']
        jg.texto2 = request.POST['texto2']
        jg.texto3 = request.POST['texto3']
        jg.texto4 = request.POST['texto4']
        jg.imagem1 = request.POST['imagem1']
        jg.imagem2 = request.POST['imagem2']
        jg.imagem3 = request.POST['imagem3']
        jg.imagem4 = request.POST['imagem4']
        jg.imagemdecapa = request.POST['imagemdecapa']
        jg.video1 = request.POST['video1']
        jg.video2 = request.POST['video2']

        jg.save()
        return HttpResponseRedirect(
            reverse('detonastrike:detalhe', args=(jg.id, )))

    context = {'jg': jg}
    return render(request, 'staticpages/update.html', context)


def delete_jogo(request, jg_id):
    jg = get_object_or_404(jogo, pk=jg_id)

    if request.method == "POST":
        jogo.delete()
        return HttpResponseRedirect(reverse('detonastrike:index'))

    context = {'jg': jg}
    return render(request, 'staticpages/delete.html', context)


def search_movies(request):
    context = {}
    if request.GET.get('query', False):
        search_term = request.GET['query'].lower()
        jogo_list = jogo.objects.filter(name__icontains=search_term)
        context = {"jogo_list": jogo_list}
    return render(request, 'staticpages/search.html', context)


class jogoListView(generic.ListView):
    model = jogo
    template_name = 'staticpages/index.html'

class jogoDetalheView(generic.DetailView):
    model = jogo
    template_name = 'staticpages/detalhe.html'

    def get_context_data(self, **kwargs):
        id = self.kwargs['pk'] 
        context = super().get_context_data(**kwargs)
        review = Review.objects.filter(jg_id=id).order_by('-data')
        context['reviews']=review
        return context


class jogoCreateView(generic.CreateView):
    model = jogo
    fields=['name','texto','release_year','texto2','texto3','texto4','poster_url','imagem1','imagem2','imagem3','imagem4','imagemdecapa','video1','video2']
    template_name = 'staticpages/create.html'

class jogoUpdateView(generic.UpdateView):
    model = jogo
    fields=['name','texto','release_year','texto2','texto3','texto4','poster_url','imagem1','imagem2','imagem3','imagem4','imagemdecapa','video1','video2']
    template_name = 'staticpages/update.html'

class jogoDeleteView(generic.DeleteView):
    model = jogo
    template_name = 'staticpages/delete.html'


@login_required
def jogoReviewView(request, jogo_id):
    jg = get_object_or_404(jogo, pk=jogo_id)
    if request.method == 'POST':
            
            author = request.user 
            texto = request.POST['text']
            data = date.today()
            rev = Review(author=author,
                            text=texto,
                            data=data,
                            jg = jg)
            rev.save()
            return HttpResponseRedirect(
                reverse('detonastrike:detalhe', args=(jg.id, )))
    else:
        context = {'jogo': jg}

    return render(request, 'staticpages/review.html', context)

#parte 3

class ListListView(generic.ListView):
    model = List
    template_name = 'staticpages/lists.html'


class ListCreateView(generic.CreateView):
    model = List
    template_name = 'staticpages/create_list.html'
    fields = ['name', 'author', 'jg']
    success_url = reverse_lazy('detonastrike:lists')

def detal(request, list_id):
    det = get_object_or_404(List, pk=list_id)
    context = {'lista': det}
    return render(request, 'staticpages/detalist.html', context)

staticpages/templates/staticpages/create.html
{% extends 'base.html' %}
{% block content %}

<div class='blocklogo'>
<h2>Adicionar jogo{{ jogo.name }}</h2>
</div>


<div class='blocklogo'>
<form method="POST" action="{% url 'detonastrike:create' %}">
    {% csrf_token %}

    <p>
        <label for="id_name">Nome do jogo:</label>
        <input type="text" name="name" id="id_name" value="{{ jogo.name }}" />
    </p>


    <p>
        <label for="id_release_year">Release year:</label>
        <input type="text" name="id_release_year" id="id_release_year" value="{{jogo.id_release_year}}" />
    </p>


    <p>
        <label for="id_texto">Texto:</label>
        <input type="text" name="texto" id="id_texto" value="{{ jogo.texto}}" />
    </p>


    <p>
        <label for="id_texto2">Texto2:</label>
        <input type="text" name="texto2" id="id_texto2" value="{{ jogo.texto2}}" />
    </p>


    <p>
        <label for="id_texto3">Texto3:</label>
        <input type="text" name="texto3" id="id_texto3" value="{{ jogo.texto3}}" />
    </p>


    <p>
        <label for="id_texto4">Texto4:</label>
        <input type="text" name="texto4" id="id_texto4" value="{{ jogo.texto4}}" />
    </p>


    <p>
        <label for="id_imagem1">Imagem1:</label>
        <input type="text" name="imagem1" id="id_imagem1" value="{{ jogo.imagem1}}" />
    </p>


    <p>
        <label for="id_imagem2">Imagem2:</label>
        <input type="text" name="imagem2" id="id_imagem2" value="{{ jogo.imagem2}}" />
    </p>



    <p>
        <label for="id_imagem3">Imagem3:</label>
        <input type="text" name="imagem3" id="id_imagem3" value="{{ jogo.imagem3}}" />
    </p>



    <p>
        <label for="id_imagem4">Imagem4:</label>
        <input type="text" name="imagem4" id="id_imagem4" value="{{ jogo.imagem4}}" />
    </p>


    <p>
        <label for="id_imagemdecapa">Imagem de capa:</label>
        <input type="text" name="imagemdecapa" id="id_imagemdecapa" value="{{ jogo.imagemdecapa}}" />
    </p>



    <p>
        <label for=" id_video1">Video1:</label>
        <input type="url" name="video1_url" id="id_video1_url" value="{{jogo.video1_url}}" />
    </p>


    <p>
        <label for=" id_video2">Video2:</label>
        <input type="url" name="video2_url" id="id_video2_url" value="{{jogo.video2_url}}" />
    </p>



    <div class='blocklogo'>
    <button type="submit">Criar</button>
    </div>

</form>


</div>
{% endblock content %}

staticpages/templates/staticpages/create_list.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block content %}

<div class='blocklogo'>
<h2>Criar categoria</h2>
</div>

<div class='blocklogo'>
<form action="{% url 'detonastrike:create_list' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <div class='blocklogo'>
    <button type="submit">Criar</button>
    </div>
</form>
</div>
{% endblock content %}

staticpages/templates/staticpages/delete.html
{% extends 'base.html' %}
{% block content %}


<div class='blocklogo'>
<form action="{% url 'detonastrike:delete' jogo.id %}" method="post">
    {% csrf_token %}

    <p>
        Você tem certeza que deseja apagar o jogo "{{ jogo.name }} ({{ jogo.release_year }})"?
    </p>


    <div class='blocklogo'>
    <button type="submit">Apagar</button>
    </div>   
    
    
</form>

</div>


{% endblock content %}

staticpages/templates/staticpages/detalhe.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<header>
    
   <h1>{{ jogo.name }}</h1>
   <a href ="{% url 'detonastrike:update' jogo.id %}" class="btn btn-lg btn-primary btn-3d">Atualizar Conteúdo</a>
   <a href ="{% url 'detonastrike:delete' jogo.id %}" class="btn btn-lg btn-primary btn-3d">Deletar Conteúdo</a>

</header>

<div class='block'>
    {{ jogo.texto }}
</div>

<div class='blocklogo'>
    {% if jogo.video1 != "/" %}
    <a href="{{ jogo.video1 }}">Link para o vídeo</a>
    {% endif %}
</div>

<div class='blocklogo'>
    {% if jogo.imagem1 != "/" %}
    <img src="{{ jogo.imagem1 }}" alt="imagem" width="800px" height="400px">
    {% endif %}
</div>
    
<div class='block'>
    {% if jogo.texto2 != "/" %}
    {{ jogo.texto2 }}
    {% endif %}
</div>

<div class='blocklogo'>
    {% if jogo.video2 != "/" %}
    <a href="{{ jogo.video2 }}">Link para o vídeo</a>
    {% endif %}
</div>

<div class='blocklogo'>
    {% if jogo.imagem2 != "/" %}
    <img src="{{ jogo.imagem2 }}" alt="imagem" width="800px" height="400px">
    {% endif %}
</div>

<div class='block'>    
    {% if jogo.texto3 != "/" %}
    {{ jogo.texto3 }}
    {% endif %}
</div>

<div class='blocklogo'>
    {% if jogo.imagem3 != "/" %}
    <img src="{{ jogo.imagem3 }}" alt="imagem" width="800px" height="400px">
    {% endif %}
</div>

<div class='block'>
    {% if jogo.texto4 != "/" %}
    {{ jogo.texto4 }}
    {% endif %}
</div>

<div class='blocklogo'>
    {% if jogo.imagem4 != "/" %}
    <img src="{{ jogo.imagem4 }}" alt="imagem" width="800px" height="400px">
    {% endif %}
</div>





<div class='blocklogo'>
    <h2>Comentários</h2>
</div>

<div class='blocklogo'>
<a href ="{% url 'detonastrike:review' jogo.id %}" class="btn btn-lg btn-primary btn-3d">Comentar</a>
</div>

<div class='block'>

    {% if reviews %}
            {% for x in reviews %}
                <figure>
                    <blockquote>
                        "{{ x.text }}"
                    </blockquote>
                    <figcaption>—{{ x.author }}, ({{ x.data }})


                </figure>
            {% endfor %}

        {% else %}

        <div class='blocklogo'>
            <p>Ainda não existe nenhum comentário para este jogo.</p>
        </div>

        {% endif %}

</div>

{% endblock content %}

staticpages/templates/staticpages/detalist.html
{% extends 'base.html' %}
{% load static %} <!-- adicione esta linha -->
{% block content %}


<div class='blocklogo'>
<h4>Jogos da categoria:</h4>
</div>
    
    <ul>
        {% if lista.jg.all %}
            {% for jogo in lista.jg.all %}
           <div class = "block"> 
            <a href ="{% url 'detonastrike:detalhe' jogo.id %}">{{jogo.name}}</a>
            {% endfor %}
            </div>
            
            {% else %}
            <p>Esta categoria não tem tutoriais ainda</p>
        {% endif %}
    </ul>

{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

        <div class='blocklogo'>
            <h1>Detona strike</h1>
        </div>  

        <div class='block'>
    Com a chegada dos videogames aos mercados, muitas pessoas se animaram em poder experimentar uma nova forma de se divertir, desestressar ou passar o tempo, e assim esse mercado cresce cada vez mais, evoluindo jogos, consoles, computadores, etc. Mas há sempre quem abandona um jogo por conta da sua dificuldade, se aborrecendo e deixando de sentir prazer ao jogar. O nosso site visa a divulgação de conteúdos do tipo tutorial, ensinando de forma simples e rápida quem procura por ajuda, desde passar uma fase, até curiosidades, segredos envolvidos, entre outros.
    Navegue pelo site e selecione os jogos de seu interesse.
        </div>

        <div class='blocklogo'>
            <a href ="{% url 'detonastrike:search' %}" class="btn btn-lg btn-primary btn-3d">Procurar</a>
        </div>

        <div class='blocklogo'>
            <a href ="{% url 'detonastrike:create' %}" class="btn btn-lg btn-primary btn-3d">Criar Conteúdo</a>
        </div>

        <div class='blocklogo'>
        <h2>Lista de Jogos</h2>
        </div>


              
            {% for jogo in jogo_list %}<div class='blocklogo'>
            <a href ="{% url 'detonastrike:detalhe' jogo.id %}" class="btn btn-lg btn-primary btn-3d">{{jogo.name}}</a>

            </div>
        
            <div class='blocklogo'>
            <img src ="{{jogo.imagemdecapa}}" alt= "{{jogo.name}}" width="800px" height="400px">
            </div>
        {% endfor %}
            
        <div class='blocklogo'>
        <a href="{% url 'detonastrike:sobre'%}" class="btn btn-lg btn-primary btn-3d">Sobre</a>
        </div>
            
    

    {% endblock content %}

staticpages/templates/staticpages/lists.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}

<div class='blocklogo'>
<h2>Listas de categorias</h2>
</div>

<section>
    {% for y in list_list %}
    <hr>
    <article>
        <header>
            <h3>{{y.name}} (de {{ y.author }}) </h3>
            <a href="{% url 'detonastrike:detalist' y.id %}"><button>Selecione</button></a>
        </header>
       
    </article>
    {% endfor %}


    <div class='blocklogo'>
    <a href="{% url 'detonastrike:create_list' %}"><button>Crie sua categoria</button></a>
    </div>
</section>

{% endblock content %}

staticpages/templates/staticpages/review.html
{% extends 'base.html' %}
{% block content %}

<div class='blocklogo'>
<h2>Comentar {{ jogo.name }} ({{ jogo.release_year }})</h2>
</div>


<form action="{% url 'detonastrike:review' jogo.id %}" method="post">
    {% csrf_token %}

    <p>
        <div class='blocklogo'>
        <label for="id_text">Comentário:</label>
        </div>

        <div class='blocklogo'>
        <input type="text" name="text" id="id_text" value="{{ jogo.text }}" />
        </div>

    </p>

    <div class='blocklogo'>
    <button type="submit">Adicionar comentário</button>
    </div>
</form>

<div class='blocklogo'>
    <p><a href="{% url 'detonastrike:detalhe' jogo.id %}">Voltar para a página do jogo</a></p>
</div>


{% endblock content %}

staticpages/templates/staticpages/search.html
{% extends 'base.html' %}
{% load static %} <!-- adicione esta linha -->
{% block content %}

<div class='blocklogo'>
<h2>Qual jogo procura?</h2>
</div>

<div class='blocklogo'>
<form action="{% url 'detonastrike:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <div class='blocklogo'>
    <button type="submit">Buscar</button>
    </div>
</form>
</div>


<div class='blocklogo'>
<h2>Resultados da Busca</h2>
</div>

<div class='blocklogo'>
{% if jogo_list %}
</div>



{% for jogo in jogo_list %}<div class='blocklogo'>
        <a href ="{% url 'detonastrike:detalhe' jogo.id %}">{{jogo.name}}</a>
        </div>
{% endfor %}


{% else %}
<div class='blocklogo'>
<p>Não foi encontrado nenhum tutorial com esse título</p>
</div>
{% endif %}

{% endblock content %}

staticpages/templates/staticpages/sobre.html
{% extends 'base.html' %}
{% block content %}

<header>
    <div class='blocklogo'>
    Olá, somos o Detona Strike, e estamos aqui para te ensinar alguns tópicos sobre os jogos que você gosta e tem curiosiosidade em descobrir coisas "ocultas" que muitos ainda não sabem!
    </div>
</header>

{% endblock content %}

staticpages/templates/staticpages/update.html
{% extends 'base.html' %}
{% block content %}

<div class='blocklogo'>
<h2>Atualizar dados jogo "{{ jogo.name }}" </h2>
</div>


<div class='blocklogo'>
<form method="POST" action="{% url 'detonastrike:update' jogo.id %}">
    {% csrf_token %}

    <p>
        <label for="id_name">Nome do jogo:</label>
        <input type="text" name="name" id="id_name" value="{{ jogo.name }}" />
    </p>


    <p>
        <label for="id_release_year">Release year:</label>
        <input type="text" name="id_release_year" id="id_release_year" value="{{jogo.id_release_year}}" />
    </p>


    <p>
        <label for="id_texto">Texto:</label>
        <input type="text" name="texto" id="id_texto" value="{{ jogo.texto}}" />
    </p>


    <p>
        <label for="id_texto2">Texto2:</label>
        <input type="text" name="texto2" id="id_texto2" value="{{ jogo.texto2}}" />
    </p>


    <p>
        <label for="id_texto3">Texto3:</label>
        <input type="text" name="texto3" id="id_texto3" value="{{ jogo.texto3}}" />
    </p>


    <p>
        <label for="id_texto4">Texto4:</label>
        <input type="text" name="texto4" id="id_texto4" value="{{ jogo.texto4}}" />
    </p>


    <p>
        <label for="id_imagem1">Imagem1:</label>
        <input type="text" name="imagem1" id="id_imagem1" value="{{ jogo.imagem1}}" />
    </p>


    <p>
        <label for="id_imagem2">Imagem2:</label>
        <input type="text" name="imagem2" id="id_imagem2" value="{{ jogo.imagem2}}" />
    </p>



    <p>
        <label for="id_imagem3">Imagem3:</label>
        <input type="text" name="imagem3" id="id_imagem3" value="{{ jogo.imagem3}}" />
    </p>



    <p>
        <label for="id_imagem4">Imagem4:</label>
        <input type="text" name="imagem4" id="id_imagem4" value="{{ jogo.imagem4}}" />
    </p>


    <p>
        <label for="id_imagemdecapa">Imagem de capa:</label>
        <input type="text" name="imagemdecapa" id="id_imagemdecapa" value="{{ jogo.imagemdecapa}}" />
    </p>



    <p>
        <label for=" id_video1">Video1:</label>
        <input type="url" name="video1_url" id="id_video1_url" value="{{jogo.video1_url}}" />
    </p>


    <p>
        <label for=" id_video2">Video2:</label>
        <input type="url" name="video2_url" id="id_video2_url" value="{{jogo.video2_url}}" />
    </p>



    <div class='blocklogo'>
    <button type="submit">Atualizar</button>
    </div>

</form>


</div>
{% endblock content %}