detonastrike/urls.py
from django.contrib import admin
from django.urls import include, path # modificar esta linha

urlpatterns = [
    path('', include('staticpages.urls')), # adicionar esta linha
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path
from . import views

app_name = 'detonastrike'

urlpatterns = [
    path('', views.jogoListView.as_view(), name='index'),
    path('search/', views.search_movies, name='search'),
    path('<int:pk>/', views.jogoDetalheView.as_view(), name='detalhe'),
    path('create/', views.jogoCreateView.as_view(), name='create'),
    path('update/<int:pk>/', views.jogoUpdateView.as_view(), name='update'),
    path('delete/<int:pk>/', views.jogoDeleteView.as_view(), name='delete'),
    path('review/<int:jogo_id>/', views.jogoReviewView, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
    path('lists/create/', views.ListCreateView.as_view(), name='create_list'),
    path('detalist/<int:list_id>/', views.detal, name='detalist'),

    #path('<int:jg_id>/', views.detalhe, name='detalhe'),
    path('sobre', views.sobre, name='sobre'),
    #path('create', views.create_jogo, name='create'),
    #path('update/<int:jg_id>/', views.update_jogo, name='update'),
    #path('delete/<int:jg_id>/', views.delete_jogo, name='delete'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">  
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <nav class="navbar navbar-expand-md navbar-light bg-light"></nav>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>

<body>
    <div class='blocklogo'>
    <a href="{% url 'detonastrike:index'%}" class="nav-item nav-link active"><img src="/static/D.png" alt="logo", width= "150px"></a>    
    </div>   

    <div class='block'>
    <a href="{% url 'detonastrike:lists' %}" class="btn btn-lg btn-primary btn-3d">Categorias</a> <!-- adicionar esta linha -->
    </div>

<section>
    
    {% block content %}
    {% endblock content %}
    
</section>


<footer>
    <p>Copyright 2021 Me.</p>
</footer>



</body>
</html>